import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");
const cssRoot = path.join(root, "assets/css");

const parts = [
  fs.readFileSync(path.join(cssRoot, "shared/site-core.css"), "utf8"),
  "\n/* === everwild: home === */\n",
  fs.readFileSync(path.join(cssRoot, "pages/home.css"), "utf8"),
  "\n/* === everwild: legal === */\n",
  fs.readFileSync(path.join(cssRoot, "pages/legal.css"), "utf8"),
  "\n/* === everwild: fuji-climbing === */\n",
  fs.readFileSync(path.join(cssRoot, "pages/fuji-climbing.css"), "utf8"),
  "\n"
];

let out = parts.join("");
out = out.replace(/url\("\.\.\/\.\.\/fonts\//g, 'url("../fonts/');
out = out.replace(/url\('\.\.\/\.\.\/fonts\//g, "url('../fonts/");

const banner = "/* Generated by npm run build:css — edit assets/css/shared/site-core.css and assets/css/pages/*.css */\n";
fs.writeFileSync(path.join(cssRoot, "site.css"), banner + out);
console.log("build-css -> assets/css/site.css (" + out.length + " chars)");
